export enum CollateralCondition {
  HIGH_QUALITY = "highQuality/Alta calidad",
  LOW_QUALITY = "lowQuality/Baja calidad",
  STABLE = "stable/Estable",
  DEPRECIATING = "depreciating/Devaluándose",
  LIQUID = "liquid/Líquido",
  ILLIQUID = "illiquid/Ilíquido",
  LOW_RISK = "lowRisk/Bajo riesgo",
  HIGH_RISK = "highRisk/Alto riesgo",
  EASILY_RECOVERABLE = "easily recoverable/Fácil de recuperar",
  DIFFICULT_TO_SEIZE = "difficult to seize/Difícil de incautar",
  VOLATILE = "volatile/Volátil",
  SECURE = "secure/Seguro",
  UNDERVALUED = "undervalued/Subvalorado",
  OVERVALUED = "overvalued/Sobrevalorado",
  APPRECIATING = "appreciating/Apreciándose",
  DEPRECIATING_RAPIDLY = "depreciating rapidly/Devaluándose rápidamente",
  DIVERSIFIED = "diversified/Diversificado",
  CONCENTRATED = "concentrated/Concentrado",
}
